abap-observability-tools/abap-metrics-provider

src/zcl_amp_metric_example.clas.xml

presumply accidentally happened through a logon in german :)

change language from D to E

---

src/zamp_metrics_provider.prog.abap
src/zcl_amp_customizing.clas.abap
src/zcl_amp_customizing.clas.xml
src/zcl_amp_customizing_base.clas.abap
src/zcl_amp_customizing_base.clas.xml
src/zcl_amp_strategist.clas.abap

https://github.com/Goala/abap-metrics-provider/issues/16
customizing wrapper created and integrated in the metric collector stategist

customizing wrapper created

---

README.md
src/zcl_amp_scraper.clas.abap

Scenario in scrapper

---

src/amp_collector/zcl_amp_c_workloads.clas.abap
src/amp_collector/zif_amp_collector.intf.abap
src/zcl_amp_strategist.clas.abap

Closes https://github.com/Goala/abap-metrics-provider/issues/50

Pass current run to collectors

---

src/amp_converter/zcl_amp_conv_prom_keyvalue.clas.abap

prometheus converter implementation added

---

src/zcl_amp_customizing.clas.abap

Removed dependency to abap-log-exporter.

Fix type of scenario.

---

src/amp_converter/zcl_amp_conv_http_json.clas.abap
src/amp_converter/zcl_amp_conv_prom_keyvalue.clas.abap

scenario added to converter

---

src/zamp_collector/zcl_amp_c_sql_monitor.clas.abap
src/zamp_collector/zcl_amp_c_sql_monitor.clas.xml

Implemented first metric of issue https://github.com/Goala/abap-metrics-provider/issues/29 (total DB time)

Added new collector for SQL monitor

---

docs/README.md

https://github.com/Goala/abap-metrics-provider/issues/29

added docs for SQL monitor

---

docs/README.md
src/zamp_collector/zcl_amp_c_transactional_rfcs.clas.abap
src/zamp_collector/zcl_amp_c_transactional_rfcs.clas.xml

#83
Example dashboard is still missing.

Sm58 collector

---

CONTRIBUTING.md

Next step in the community profile :)
https://github.com/Goala/abap-metrics-provider/community

contribution file added

---

src/zamp_converter/zcl_amp_conv_http_json.clas.abap
src/zamp_converter/zcl_amp_conv_prom_keyvalue.clas.abap
src/zamp_converter/zif_amp_converter.intf.abap
src/zamp_scraper/zcl_amp_scraper.clas.abap

content type from converter to scrapper added

---

CONTRIBUTING.md
README.md

closes https://github.com/abap-observability-tools/abap-metrics-provider/issues/96
closes https://github.com/abap-observability-tools/abap-metrics-provider/issues/88

Update links and readme

---

src/zamp_collector/zcl_amp_c_jobs.clas.abap
src/zamp_collector/zcl_amp_collector_utils.clas.abap
src/zamp_collector/zcl_amp_collector_utils.clas.xml

closes https://github.com/abap-observability-tools/abap-metrics-provider/issues/81

Init metrics

---

src/zamp_collector/zcl_amp_c_bal_logs.clas.abap
src/zamp_collector/zcl_amp_c_bal_logs.clas.xml
src/zamp_collector/zcl_amp_c_jobs.clas.abap
src/zamp_collector/zcl_amp_c_runtime_errors.clas.abap

closes https://github.com/abap-observability-tools/abap-metrics-provider/issues/8

Add bal collector

---

src/zamp_customizing/zampv_config_prov.tobj.xml
src/zamp_customizing/zampv_config_scev.tobj.xml

customzing standard recording routine added

---

docs/README.md
local-tests/grafana/dashboards/examples_influxdb/transport_states.json
src/zamp_collector/zcl_amp_c_transport_states.clas.abap
src/zamp_collector/zcl_amp_c_transport_states.clas.xml

Transport states

---

local-tests/grafana/dashboards/examples_influxdb/transactional_rfcs.json

example dashboard for transactional RFCs added

---

docs/README.md
local-tests/grafana/dashboards/examples_influxdb/bal_logs.json

closes https://github.com/abap-observability-tools/abap-metrics-provider/issues/8

Add dashboard example

---

src/zamp_collector/zcl_amp_c_work_processes.clas.abap
src/zamp_collector/zcl_amp_c_work_processes.clas.xml

#31
docu and example dashboard will be follow later.

collector SM50 work processes added

---

docs/README.md
local-tests/grafana/dashboards/examples_influxdb/bal_logs.json
src/zamp_collector/zcl_amp_c_bal_logs.clas.abap

closes https://github.com/abap-observability-tools/abap-metrics-provider/issues/113

Add bal msgty metric

---

src/zamp_collector/zcl_amp_c_transactional_rfcs.clas.abap

initialisation of metrics added

---

src/zamp_provider/zcl_amp_strategist.clas.abap

clear table after append to total table

---

docs/README.md
src/zamp_collector/zcl_amp_c_batch_input.clas.abap
src/zamp_collector/zcl_amp_c_batch_input.clas.xml

Don't close  https://github.com/abap-observability-tools/abap-metrics-provider/issues/109
I will provide an example dashboard with another pull request
Open ToDos:

Add batch input metrics

---

src/zamp_collector/zcl_amp_c_queued_rfcs.clas.abap

name differentiation forgotten in #121

metric name for inbound and outbound

---

abaplint.json
package-lock.json
package.json
src/zamp_collector/zcl_amp_c_bal_logs.clas.abap
src/zamp_provider/zcl_amp_strategist.clas.abap
src/zamp_scraper/zcl_amp_scraper.clas.abap

some are still left. keep #127 open

abaplint update and fixes

---

src/zamp_auth/zcl_amp_auth_checker.clas.abap

auth fix confusion scraper with provider

---

docs/README.md

auth docu added

---

pull_request_template.md

https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

pull request template created

---

README.md

snyk badge removed

---

abaplint.json

the disabled rules with the issues can be checked here: https://abaplint.app/stats/abap-observability-tools/abap-metrics-provider/disabled_rules
Little by little we can then activate them again.

disabled some abaplint rules

---

docs/README.md

related issue: -
In case of a metric:

Link to abaplint collector UML added

---

docs/README.md

related issue: -
In case of a metric:

Link to abaplint converter UML added

---

README.md

related issue: -
In case of a metric:

youtubevideo link in readme added

---

abaplint.json
src/zamp_collector/zcl_amp_c_runtime_errors.clas.abap
src/zamp_converter/zcl_amp_conv_http_json.clas.testclasses.abap
src/zamp_provider/zcl_amp_strategist.clas.abap

related issue: closes #127
In case of a metric:

abaplint rules disabled and some little fixes

---

src/zamp_store/zamp_clear_zamp_store.prog.abap
src/zamp_store/zamp_clear_zamp_store.prog.xml

related issue: 
closes #51 
closes #103

metrics delete prog depending on timestamp added

---

local-tests/README.md

local-test readme curl command added to drop data from influxdb

readme influxdb util curl drop data added

---

.github/workflows/update-changelog.yml
package-lock.json
package.json

related issue: #157 
automatic changelog update

github action automatic changelog updated added

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

related issue: #157
automatic release drafts

release-drafter added

---

.github/workflows/update-changelog.yml

first part of #161 
auto merging will maybe come later

pull request for changelog changes

---

.github/release-drafter.yml

category misc for non ABAP added

---

README.md

To see the full set of videos :)

Readme Link to Playlist changed

---

README.md

badge for the codeCov stats uploaded with https://github.com/larshp/abapCov

codeCov badge added

---

.github/dependabot.yml

dependabot configuration added

---

package-lock.json
package.json

abaplint npm package removed
